export const ERROR_CODES = {
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    HASH_ERROR: 'HASH_ERROR',
    TOO_MANY_REQUESTS:'TOO_MANY_REQUESTS',
    TOO_MANY_LOGIN_ATTEMPTS:'TOO_MANY_LOGIN_ATTEMPTS',
    NOT_FOUND:'NOT_FOUND'
} as const;


export const VALIDATION_ERROR_CODES = {
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    PASSWORD_COMPARISON_ERROR:'PASSWORD_COMPARISON_ERROR',
    USERNAME_EXISTS: 'USERNAME_EXISTS',
    EMAIL_EXISTS:'EMAIL_EXISTS'
}


export const MONGO_ERROR_CODES = {
    E11000: 'DUPLICATE_KEY_ERROR',
    DB_PING_ERROR:'DB_PING_ERROR',
    DB_DISCONNECTION_ERROR:'DB_DISCONNECTION_ERROR',
    DB_CONNECTION_ERROR:'DB_CONNECTION_ERROR',
    DB_CHECK_ERROR: 'DB_CHECK_ERROR',
}

export const USER_CODES = {
    USER_REGISTERED:'USER_REGISTERED',
    INVALID_CREDENTIALS:'INVALID_CREDENTIALS',
    INVALID_PASSWORD:'INVALID_PASSWORD',
}


export const REDIS_ERROR_CODES = {
    REDIS_NOT_INITIALIZED: 'REDIS_NOT_INITIALIZED',
    INVALID_REDIS_CLIENT_URL:'INVALID_REDIS_CLIENT_URL'
}

export type MongoErrorCode = typeof MONGO_ERROR_CODES[keyof typeof MONGO_ERROR_CODES];
export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
