export const CONSTANTS = {
    TITLE: 'title',
    CONTENT: 'content',
    POST_ID: 'postId',
    TEXT: 'text',
    COMMENT_ID: 'commentId',
    SORT_BY: 'sortBy',
    SORT_ORDER: 'sortOrder',
    CREATED_AT: 'createdAt',
    REPLIES_COUNT: 'repliesCount',
    ASC: 'asc',
    DESC: 'desc',
    PAGE: 'page',
    PAGE_SIZE: 'pageSize',
}